# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 16:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orientation', models.IntegerField()),
                ('url', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('year', models.IntegerField()),
                ('autor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitud', models.FloatField()),
                ('longitud', models.FloatField()),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('type', models.CharField(max_length=30)),
                ('represent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfg.Image')),
            ],
        ),
        migrations.AddField(
            model_name='image',
            name='id_marker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfg.Marker'),
        ),
        migrations.AddField(
            model_name='image',
            name='id_street',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tfg.Street'),
        ),
    ]
