# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-18 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0002_auto_20160518_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='type',
            field=models.CharField(choices=[('CALLE', 'Calle'), ('AVENIDA', 'Avenida'), ('CALLEJON', 'Callejon'), ('CAMINO', 'Camino'), ('PASEO', 'Paseo'), ('TRAVESIA', 'Travesia'), ('PLAZA', 'Plaza'), ('PASADIZO', 'Pasadizo')], default='CALLE', max_length=30),
        ),
    ]
