# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-24 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0005_auto_20160520_1058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='type',
            field=models.CharField(choices=[('SIN', '- Ninguno -'), ('CALLE', 'Calle'), ('AVENIDA', 'Avenida'), ('CALLEJON', 'Callejon'), ('CAMINO', 'Camino'), ('PASEO', 'Paseo'), ('TRAVESIA', 'Travesia'), ('PLAZA', 'Plaza'), ('PASADIZO', 'Pasadizo'), ('PASAJE', 'Pasaje')], default='CALLE', max_length=30),
        ),
    ]
