# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-25 16:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0007_auto_20160525_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='/medi', upload_to='/media'),
        ),
    ]
