# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 09:01
from __future__ import unicode_literals

from django.db import migrations, models
import tfg.models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0011_auto_20160525_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tfg.models.upload_to, verbose_name='image'),
        ),
    ]
