# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0014_auto_20160606_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='represent',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
