# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-07 14:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0015_auto_20160606_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='type',
            field=models.CharField(choices=[(b'CALLE', b'Calle'), (b'AVENIDA', b'Avenida'), (b'CALLEJON', b'Callejon'), (b'CAMINO', b'Camino'), (b'PASEO', b'Paseo'), (b'TRAVESIA', b'Travesia'), (b'PLAZA', b'Plaza'), (b'PASADIZO', b'Pasadizo'), (b'PASAJE', b'Pasaje')], default=b'CALLE', max_length=30, null=True),
        ),
    ]
