# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-09 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0016_auto_20160607_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='type',
        ),
        migrations.AddField(
            model_name='marker',
            name='num_images',
            field=models.IntegerField(null=True),
        ),
    ]
