# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import tfg.models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0018_auto_20160610_1821'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='latitud',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='longitud',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to=tfg.models.upload_to),
        ),
        migrations.AlterField(
            model_name='marker',
            name='num_images',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='street',
            name='represent',
            field=models.CharField(max_length=120),
        ),
    ]
