# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 16:45
from __future__ import unicode_literals

from django.db import migrations, models
import tfg.models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0024_auto_20160613_1841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=tfg.models.upload_to),
        ),
        migrations.AlterField(
            model_name='marker',
            name='num_images',
            field=models.IntegerField(null=True),
        ),
    ]
