# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-13 17:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0026_auto_20160613_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='street',
            name='latitud',
            field=models.FloatField(default=41),
        ),
        migrations.AddField(
            model_name='street',
            name='longitud',
            field=models.FloatField(default=-4),
        ),
    ]
