# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0028_auto_20160613_1908'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='title',
            new_name='title_es',
        ),
        migrations.RenameField(
            model_name='marker',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RenameField(
            model_name='marker',
            old_name='title',
            new_name='title_es',
        ),
        migrations.RenameField(
            model_name='street',
            old_name='description',
            new_name='description_en',
        ),
        migrations.RemoveField(
            model_name='street',
            name='name',
        ),
        migrations.AddField(
            model_name='image',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='description_es',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='marker',
            name='title_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='name_en',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='street',
            name='name_es',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
