# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 10:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0029_auto_20160617_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='name_en',
            field=models.CharField(default='calle', max_length=50),
            preserve_default=False,
        ),
    ]
