# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-25 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0030_auto_20160617_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='street',
            name='represent',
            field=models.CharField(max_length=120),
        ),
    ]
