# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-30 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0031_auto_20160625_1535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='name_en',
        ),
    ]
