# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-05 10:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0032_remove_street_name_en'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='street',
            name='latitud',
        ),
        migrations.RemoveField(
            model_name='street',
            name='longitud',
        ),
    ]
