# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-07 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tfg', '0034_auto_20160707_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marker',
            name='description_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='marker',
            name='description_es',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
